import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase';
import type { VideoAnalysis, SummaryPoint } from '@/lib/supabase';

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const format = req.nextUrl.searchParams.get('format') || 'markdown';
  const { id } = params;

  const { data, error } = await supabaseAdmin
    .from('video_analyses')
    .select('*')
    .eq('id', id)
    .single();

  if (error || !data) {
    return NextResponse.json({ error: 'Analysis not found' }, { status: 404 });
  }

  const analysis = data as VideoAnalysis;

  if (format === 'markdown') {
    const md = buildMarkdown(analysis);
    return new NextResponse(md, {
      headers: {
        'Content-Type': 'text/markdown',
        'Content-Disposition': `attachment; filename="analysis-${id.slice(0, 8)}.md"`,
      },
    });
  }

  // JSON export
  return NextResponse.json(analysis, {
    headers: {
      'Content-Disposition': `attachment; filename="analysis-${id.slice(0, 8)}.json"`,
    },
  });
}

function buildMarkdown(a: VideoAnalysis): string {
  const date = new Date(a.created_at).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  const categories = (a.categories || []).map((c) => `\`${c}\``).join(', ');

  let md = `# ${a.title || 'YouTube Video Analysis'}\n\n`;
  md += `**Channel:** ${a.channel_name || 'Unknown'}  \n`;
  md += `**Duration:** ${a.duration || 'Unknown'}  \n`;
  md += `**URL:** ${a.url}  \n`;
  md += `**Analyzed:** ${date}  \n`;
  md += `**Categories:** ${categories || 'None'}  \n`;
  md += `**Transcript:** ${a.transcript_available ? 'Available' : 'Not available — AI vision analysis'}  \n\n`;
  md += `---\n\n`;

  if (a.key_insights?.length) {
    md += `## Key Insights\n\n`;
    a.key_insights.forEach((insight) => {
      md += `- ${insight}\n`;
    });
    md += `\n`;
  }

  if (a.summary?.length) {
    md += `## Cliff Notes\n\n`;
    (a.summary as SummaryPoint[]).forEach((point) => {
      const tsLink = `[${point.timestamp}](https://www.youtube.com/watch?v=${a.video_id}&t=${Math.floor(point.timestamp_ms / 1000)}s)`;
      md += `### ${tsLink}\n`;
      md += `${point.point}\n`;
      if (point.visual_context) {
        md += `> 📊 **Visual:** ${point.visual_context}\n`;
      }
      md += `\n`;
    });
  }

  if (a.visual_moments?.length) {
    md += `## Notable Visual Moments\n\n`;
    a.visual_moments.forEach((vm) => {
      md += `- **${vm.timestamp}** — ${vm.description}\n`;
    });
    md += `\n`;
  }

  md += `---\n*Generated by YouTube Video Analyzer — SignalStrike*\n`;
  return md;
}
